### ISSUE TITLE
Documentação de contexto

### ISSUE THREAD

**Issue by Carol-Novaes** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e3-proj-mov-t4-fuel#2]
Realizar os seguintes tópicos: 

- Contexto  
- O problema  
- Os objetivos 
- A justificativa 
- Público-alvo

**Comment by RuanGonzaga** [comment]
Criando a nossa Documentação de Contexto seguindo os tópicos listados!

**Comment by RuanGonzaga** [comment]
Documentação de Contexto finalizada e pronta para revisão! Já colocada no github!
